### ISSUE TITLE
What license is this code released under? (and do you have copyright)

### ISSUE THREAD

**Issue by geeksville** [Lawmate/BQ25703A#2]
Hi,

I'm interested in using this in our www.meshtastic.org project.  But I wanted to check what license terms you are using?  GPL?  MIT?  Totally public domain?

Also, I'll send you a pull request soon with some minor changes needed to work on NRF52 CPUs.

**Comment by Lawmate** [comment]
Hey, thanks for the interest. I've updated the license to GPL and have merged the requests. Your project looks very cool. The only thing I would say is that while the BQ25703A is pretty nice to use, once you have all the passives, it's not super cheap.
Let me know your thoughts if you need to fiddle with the library. I haven't written very many libraries and this and the BQ4050 one are the first that I have done with an effort to be in c++. The registers in the datasheet are presented as being classes and sub classes, so I decided to contain the values as nested structs in the header file. All the functions are then template functions that manipulate the common format of the structs. I don't know if this is an overly complicated way to do things and am pretty new to a lot of the coding concepts, so let me know your thoughts if you do delve into it.

**Comment by geeksville** [comment]
will do!  I haven't yet received the new board that has this part installed - I should receive it in a couple of weeks.

**Comment by geeksville** [comment]
btw - an update on this.  alas, the board I was helping with that used this part had some other problems, so the mfg is respinning and using a different PMU in the new design.  So I won't be using your cool project after all.
